name:                Baum-proto
version:             0.1.0.0
github:              "githubuser/Baum-proto"
license:             BSD-3-Clause
author:              phi16
maintainer:          "phi16.256@gmail.com"
copyright:           "2024 phi16"

dependencies:
- base >= 4.7 && < 5

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: src
  dependencies:
  - containers

executables:
  Baum-proto-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - Baum-proto

default-extensions:
  - GADTs